Repository OpenSource-THG/camel, pull requests merged in 2019-03, with the labels that each got.

#1 Add pulsar uri parsing class
  components/camel-pulsar/pom.xml
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarComponent.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarUri.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/configuration/PulsarEndpointConfiguration.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/TopicTypeUtils.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarComponentTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarUriTest.java
Labels: rain, ready to merge

#4 Example code for pulsar
  components/camel-pulsar/pom.xml
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarComponent.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarEndpoint.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarProducer.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarUri.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/configuration/AdminConfiguration.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/configuration/PulsarEndpointConfiguration.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/AutoConfiguration.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/consumers/CommonCreationStrategy.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarComponentTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarEndpointTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarUriTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/AutoConfigurationTest.java
  examples/camel-example-spring-pulsar/README.md
  examples/camel-example-spring-pulsar/pom.xml
  examples/camel-example-spring-pulsar/src/main/java/org/apache/camel/example/pulsar/client/CamelClient.java
  examples/camel-example-spring-pulsar/src/main/java/org/apache/camel/example/pulsar/client/CamelClientEndpoint.java
  examples/camel-example-spring-pulsar/src/main/java/org/apache/camel/example/pulsar/server/Multiplier.java
  examples/camel-example-spring-pulsar/src/main/java/org/apache/camel/example/pulsar/server/ServerRoutes.java
  examples/camel-example-spring-pulsar/src/main/java/org/apache/camel/example/pulsar/server/Treble.java
  examples/camel-example-spring-pulsar/src/main/resources/META-INF/LICENSE.txt
  examples/camel-example-spring-pulsar/src/main/resources/META-INF/NOTICE.txt
  examples/camel-example-spring-pulsar/src/main/resources/META-INF/spring/camel-server.xml
  examples/camel-example-spring-pulsar/src/main/resources/camel-client.xml
  examples/camel-example-spring-pulsar/src/main/resources/camel.properties
  examples/camel-example-spring-pulsar/src/main/resources/features.xml
  examples/camel-example-spring-pulsar/src/main/resources/log4j.properties
  examples/camel-example-spring-pulsar/src/test/java/org/apache/camel/example/SpringJmsClientServerTest.java
  examples/pom.xml
Labels: rain, ready to merge

#7 VGR-10914 2.17.3 pulsar producer message serialization
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarComponent.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarConsumer.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarEndpoint.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarMessageListener.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarProducer.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/configuration/PulsarEndpointConfiguration.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/AutoConfiguration.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/PulsarUtils.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/consumers/CommonCreationStrategyUtils.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/consumers/ConsumerCreationStrategyFactory.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/consumers/ExclusiveConsumerStrategy.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/consumers/FailoverConsumerStrategy.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/consumers/SharedConsumerStrategy.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/retry/ExponentialRetryPolicy.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/retry/PulsarClientRetryPolicy.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarComponentTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarConsumerInTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/PulsarUtilsTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/consumers/CommonCreationStrategyUtilsTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/consumers/ConsumerCreationStrategyFactoryTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/consumers/ExclusiveConsumerStrategyTest.java
  components/camel-pulsar/src/test/resources/log4j.properties
  components/camel-pulsar/src/test/resources/log4j2-test.xml
Labels: rain, wip

#9 Fix producer serialization for none strings
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarProducer.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/message/PulsarMessageUtils.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/message/PulsarMessageUtilsTest.java
Labels: needs review, rain

#11 Merge Kev's TODO comments into main dev branch
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarComponent.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarConsumer.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarEndpoint.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarMessageListener.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarProducer.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/configuration/PulsarEndpointConfiguration.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/AutoConfiguration.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/PulsarUtils.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/TopicTypeUtils.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/consumers/CommonCreationStrategyUtils.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/consumers/ExclusiveConsumerStrategy.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarConsumerInTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/AutoConfigurationTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/PulsarUtilsTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/consumers/CommonCreationStrategyUtilsTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/consumers/ConsumerCreationStrategyFactoryTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/consumers/ExclusiveConsumerStrategyTest.java
  examples/camel-example-spring-pulsar/src/main/java/org/apache/camel/example/pulsar/server/Treble.java
Labels: rain, ready to merge

#13 No more synchronised blocks
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/PulsarProducer.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/configuration/PulsarEndpointConfiguration.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/PulsarUtils.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/TopicTypeUtils.java
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/utils/message/PulsarMessageHeaders.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarConcurrentProducerInTest.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/utils/PulsarUtilsTest.java
Labels: needs review, rain

#14 Default values for endpoint configuration
  components/camel-pulsar/src/main/java/org.apache.camel.component.pulsar/configuration/PulsarEndpointConfiguration.java
  components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarComponentTest.java
Labels: needs review, rain
